
services:
  nginx-service:
    build: ./nginx
    image: nginx-ubuntu-servers
    ports:
      - "8081:8081"
      - "8082:8082"
    restart: always
  
  tester-service:
    build: ./testing
    image: go-tester
    depends_on:
      - nginx-service
    
    environment:
      - SERVER1_URL=${SERVER1_URL}
      - SERVER2_URL=${SERVER2_URL}