events {}
http {
    server {
        # Server number one on port 8081, responds with a custom html response.
        listen 8081;

        location / {
            add_header Content-Type text/html;
            return 200 '<html><body><h1>Hello F5ers!</h1></body></html>';
        }
        
    }
    server {
        # Server number two on port 8082, responds with an HTTP error code.
        listen 8082;

        location / {
            return 503;
        }
    }
}